name: Run Pipeline

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: "Client ID"
        required: true
        type: string
      issue_number:
        description: "Issue Number"
        required: false
        type: string
      issue_url:
        description: "Issue URL"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print inputs
        run: |
          echo "Client ID: ${{ inputs.client_id }}"
          echo "Issue Number: ${{ inputs.issue_number }}"
          echo "Issue URL: ${{ inputs.issue_url }}"
